import { PageShell } from "@/components/layout/page-shell";
import { requireRole } from "@/lib/auth/session";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ReferralsQueue } from "@/components/admin/referrals-queue";

export default async function AdminReferralsPage() {
  await requireRole("admin");

  return (
    <PageShell>
      <h1 className="text-3xl font-semibold tracking-tight">Admin · Referrals queue</h1>
      <p className="mt-2 text-muted-foreground">
        Manage underwriting referrals generated by quote assumptions and specialist covers.
      </p>
      <Card className="mt-8">
        <CardHeader>
          <CardTitle>Referrals</CardTitle>
        </CardHeader>
        <CardContent>
          <ReferralsQueue />
        </CardContent>
      </Card>
    </PageShell>
  );
}
