import type { QuoteApplicationPayload } from "@/lib/domain/quote";

export const defaultQuoteDraft: QuoteApplicationPayload = {
  your_details: {
    is_new_or_renewing: "Joining for first time",
    title: "Ms",
    first_name: "",
    last_name: "",
    org_name: "",
    correspondence_address: {
      postcode: "",
      line1: "",
      line2: "",
      town: "",
      county: "",
    },
    email: "",
    email_confirm: "",
    password: "",
    password_confirm: "",
    mobile_number: "",
    alternative_number: "",
    job_role: "Manager",
    start_date: "",
  },
  general: {
    main_site: {
      setting_main_activity: "Full-year day care provision",
      setting_address: {
        postcode: "",
        line1: "",
        line2: "",
        town: "",
        county: "",
      },
      is_domestic_premises: "Non-domestic",
      legal_status: "Limited Company",
      ofsted_number: "",
    },
    additional_services: {
      has_wraparound_provision: false,
      has_holiday_club: false,
      has_baby_toddler: false,
      has_forest_school: false,
    },
    accepts_membership_declaration: false,
    wants_insurance_quote: true,
    insurance_questions: {
      is_outdoor_provision: false,
      ages_0_3: false,
      ages_3_5: false,
      ages_5_11: false,
      ages_12_plus: false,
      annual_turnover: 0,
      contents_equipment_value: 0,
      wants_extra_public_liability_10m: false,
      professional_indemnity_level: "None",
      wants_wraparound_cover: false,
      wants_holiday_club_cover: false,
      wants_shed_outbuildings_cover: "None",
      wants_computer_cover_10k: false,
      wants_childrens_parties_cover: false,
      wants_outside_play_equipment_cover: true,
      wants_abuse_cover: false,
      wants_terrorism_cover: false,
      wants_fidelity_cover: false,
      wants_main_building_insurance: false,
      wants_additional_building_insurance: false,
      claims_last_5_years: "0",
    },
    additional_sites: [],
  },
  assumptions: {
    assumption_bankrupt: false,
    assumption_receiver: false,
    assumption_disqualified: false,
    assumption_criminal: false,
    assumption_insurance_cancelled: false,
    assumption_claim_circumstances: false,
    assumption_employee_warning: false,
  },
  declaration: {
    agrees_demands_needs: false,
    agrees_declaration: false,
  },
  ern: {
    is_ern_exempt: false,
    ern_number: "",
  },
  payment_method: "Credit Card",
};
