import type { QuoteApplicationPayload } from "@/lib/domain/quote";

export function buildQuotePayload(
  overrides: Partial<QuoteApplicationPayload> = {},
): QuoteApplicationPayload {
  return {
    your_details: {
      is_new_or_renewing: "Joining for first time",
      title: "Ms",
      first_name: "Jane",
      last_name: "Doe",
      org_name: "Acorn Nursery",
      correspondence_address: {
        postcode: "SW1A1AA",
        line1: "1 Westminster House",
        line2: "",
        town: "London",
        county: "Greater London",
      },
      email: "jane@example.com",
      email_confirm: "jane@example.com",
      password: "StrongPass#1",
      password_confirm: "StrongPass#1",
      mobile_number: "07123456789",
      alternative_number: "",
      job_role: "Manager",
      start_date: "2026-04-01",
    },
    general: {
      main_site: {
        setting_main_activity: "Full-year day care provision",
        setting_address: {
          postcode: "SW1A1AA",
          line1: "1 Westminster House",
          line2: "",
          town: "London",
          county: "Greater London",
        },
        is_domestic_premises: "Non-domestic",
        legal_status: "Limited Company",
        ofsted_number: "OF123456",
      },
      additional_services: {
        has_wraparound_provision: true,
        has_holiday_club: false,
        has_baby_toddler: true,
        has_forest_school: false,
      },
      accepts_membership_declaration: true,
      wants_insurance_quote: true,
      insurance_questions: {
        is_outdoor_provision: false,
        ages_0_3: true,
        ages_3_5: true,
        ages_5_11: false,
        ages_12_plus: false,
        annual_turnover: 220000,
        contents_equipment_value: 45000,
        wants_extra_public_liability_10m: true,
        professional_indemnity_level: "500000",
        wants_wraparound_cover: true,
        wants_holiday_club_cover: false,
        wants_shed_outbuildings_cover: "Level 1",
        wants_computer_cover_10k: true,
        wants_childrens_parties_cover: false,
        wants_outside_play_equipment_cover: true,
        wants_abuse_cover: false,
        wants_terrorism_cover: false,
        wants_fidelity_cover: true,
        wants_main_building_insurance: false,
        wants_additional_building_insurance: false,
        claims_last_5_years: "0",
      },
      additional_sites: [],
    },
    assumptions: {
      assumption_bankrupt: false,
      assumption_receiver: false,
      assumption_disqualified: false,
      assumption_criminal: false,
      assumption_insurance_cancelled: false,
      assumption_claim_circumstances: false,
      assumption_employee_warning: false,
    },
    declaration: {
      agrees_demands_needs: true,
      agrees_declaration: true,
    },
    ern: {
      is_ern_exempt: false,
      ern_number: "123/AB4567",
    },
    payment_method: "Credit Card",
    ...overrides,
  };
}
