import { PageShell } from "@/components/layout/page-shell";
import { requireSession } from "@/lib/auth/session";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { DocumentsList } from "@/components/portal/documents-list";

export default async function PortalDocumentsPage() {
  await requireSession();

  return (
    <PageShell>
      <h1 className="text-3xl font-semibold tracking-tight">Policy documents</h1>
      <p className="mt-2 text-muted-foreground">
        Document URLs generated by Nexus Core and surfaced for member download.
      </p>
      <Card className="mt-8">
        <CardHeader>
          <CardTitle>Document vault</CardTitle>
        </CardHeader>
        <CardContent>
          <DocumentsList />
        </CardContent>
      </Card>
    </PageShell>
  );
}
